import { Sparkles } from 'lucide-react'
import type { Insight } from '../types/finance'

interface InsightCardsProps {
  insights: Insight[]
}

export function InsightCards({ insights }: InsightCardsProps) {
  if (insights.length === 0) {
    return (
      <div className="rounded-xl border border-border bg-surface p-8 text-center text-sm text-foreground/60">
        Personalized insights will appear after analysis
      </div>
    )
  }

  return (
    <div className="grid gap-4 md:grid-cols-2">
      {insights.map((insight) => (
        <article key={insight.id} className="relative rounded-xl border border-border bg-surface p-5 shadow-sm">
          {insight.source === 'llm' && (
            <div className="absolute top-5 right-5 text-secondary" title="Generated by AI">
              <Sparkles size={16} />
            </div>
          )}
          <h3 className="font-semibold text-foreground pr-8">{insight.title}</h3>
          <p className="mt-2 text-sm text-foreground-variant">{insight.body}</p>
          {insight.amount != null && (
            <p className="mt-3 text-sm font-medium text-foreground">
              ₹{insight.amount.toLocaleString('en-IN')}
            </p>
          )}
        </article>
      ))}
    </div>
  )
}
